CHANGELOG.md, components/screens/HomeScene/HomeScene.xml, components/screens/LoadingIndicator/LoadingIndicator.brs, source/config.tmpl.json, source/services/akamai/AkaMA_PluginMain.brs
- Updated code causing depreciation warnings on Roku submissions
=> Akamai update

CHANGELOG.md, components/screens/Favorites/Favorites.brs, components/screens/MyLibrary/MyLibrary.brs, components/screens/Search/Search.brs
UX bug fix. App was not focusing correct thumbnail when returning from player in Search, Favorites, or My Library
=> Index refocusing

components/screens/GridScreen/GridScreen.brs, components/screens/HomeScene/HomeScene.brs, source/helpers.brs, source/main.brs, source/zype_api.brs
Please review for the following fixes
1) fix the crash issue when there are no sliders included in the build
2) address the light vs dark theme issue 
3) address the slider size
4) slider appearing on special screens (eg:playlist screens)
=> non-slider channel crash fix , slider size fix , slider coming up on special screen 

source/themes.brs
Updating the dark theme background color to use pure black (hex #000000).
=> Set dark theme background to black color

source/playlist-model.brs, source/themes.brs, source/video-model.brs
Improved thumbnail functionality for videos with custom thumbnail images.
=> Thumbnail enhancements

source/main.brs
Reverts zype/zype-roku-scenegraph#52
=> Revert "Playlist bundle purchasing"

components/screens/DetailsScreen/DetailsScreen.brs, source/main.brs
Fixed issue of AutoPlay next video crash
=> Fixed issue of AutoPlay next video crash

components/screens/DetailsScreen/DetailsScreen.brs, source/main.brs, source/services/ZypeServices/MarketplaceConnectService.brs, source/text_labels_config.json
Add following in config.json:,
"marketplace_connect_svod": true,
"subscription_plan_ids": [
"<_ID1>",
"<_ID2>",
]
=> Implemented support of marketplace_connect_svod

components/ContentNodes/VideoNode/videonode.xml, components/screens/DetailsScreen/DetailsScreen.brs, source/main.brs, source/video-model.brs
Integrated live on_air fixes + audio only thumbnails from other branch
- Now Live will not show Ui Controls for seeking / FF / RW etc
- Now for Audio Only stream, we will show that stream poster instead of roku default player black screen
=> Integrated live on_air fixes + audio only thumbnails from other branch

components/screens/AuthSelection/AuthSelection.xml, components/screens/DetailsScreen/DetailsScreen.brs, components/screens/DetailsScreen/DetailsScreen.xml, components/screens/DeviceLinking/DeviceLinking.xml, components/screens/EPGScreen/EPGScreen.xml, components/screens/Favorites/Favorites.xml, components/screens/GridScreen/GridScreen.xml, components/screens/InfoScreen/InfoScreen.xml, components/screens/MyLibrary/MyLibrary.xml, components/screens/PurchaseScreen/PurchaseScreen.xml, components/screens/Search/Search.xml, source/main.brs, source/services/ZypeServices/MarketplaceConnectService.brs, source/text_labels_config.json
Fixed issue of Image scaleToFit order
Due to this it ws not scaling Image properly.
=> Fixed issue of Image scaleToFit order

components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml, source/main.brs
APPS-480 - Add support for measuring Roku startup launch time
=> Add support for measuring Roku startup launch time

source/config.tmpl.json, source/main.brs, source/services/Roku/RafService/RafService.brs, source/zype_api.brs
Default "video_content_genre": "Special"
set your required genres with comma separeted like "Special,Horror" etc
=> Fixes for AVOD roku certification requirements

components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml, source/dialogs/dialog.brs, source/main.brs
Fixed for dialog allow to close on OK events together with back event
=> Click OK or Back on remote to close popup dialog boxes

components/screens/GridScreen/GridScreen.brs, components/screens/GridScreen/GridScreen.xml, components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml, source/helpers.brs, source/main.brs, source/text_labels_config.json
Autoplay video as per "autoplay_hero" response
=> APPS-716 Roku: Autoplay video immediately following app splash screen

components/screens/DetailsScreen/DetailsScreen.brs, components/screens/Favorites/Favorites.xml, components/screens/Menu/Menu.brs, source/main.brs, source/text_labels_config.json
Added support for Local Favorite when "favorites_via_api": false
"favorites_via_api" from config file will be used to decide if favorite is via API or Local storage.
=> Added support for Local Favorite when "favorites_via_api": false

source/services/Roku/RafService/RafService.brs
Added replacement for LAT with ROKU_ADS_LIMIT_TRACKING roku's macro.
TODO : need to test with app which has RAF enabled.
=> Added replacement for LAT with ROKU_ADS_LIMIT_TRACKING roku's macro.

components/screens/GridScreen/GridScreen.brs, source/main.brs
=> Fixed APPS-803

source/main.brs
Implemented support for autoplay hero
=> Implemented support for autoplay hero

source/config.tmpl.json
Added marketplace_connect_svod flag into config.tmpt.json
Set appropriate values into 'subscription_plan_ids' as per your zype configuration and also enable 'marketplace_connect_svod' = true
=> Added marketplace_connect_svod flag into config.tmpt.json

components/screens/HomeScene/HomeScene.brs, source/main.brs
Fix background playback during "Communicating with servers" state
=> Fix background playback during "Communicating with servers" state

manifest, source/main.brs
APPS-896 : Evalute Roku Static Analysis and fix all errors
Added support for ROKU roInputEvent for deepLinking.
=> APPS-896 roInputEvent

source/device_linking.brs, source/main.brs, source/services/akamai/helpers_utils/AkaMA_Utility.brs
Replaced "GetDeviceUniqueId with GetChannelClientid"
=> Replaced "GetDeviceUniqueId with GetChannelClientid"

components/screens/GridScreen/GridScreenItem/GridScreenItem.brs, source/main.brs, source/playlist-model.brs
Done fixes for APPS-789 for marging in master
=> Done fixes for APPS-789 for marging in master

source/main.brs, source/services/Roku/RafService/RafService.brs
=> Fixed for setitngs 9999 as duration for Live stream

source/main.brs
=> Fixed APPS-955

components/screens/DetailsScreen/DetailsScreen.brs, components/screens/DetailsScreen/DetailsScreen.xml, source/main.brs, source/zype_api.brs
Implemented this into Details screen for MP3 stream type
=> Audio only playerbackground

components/screens/Menu/Menu.brs, source/main.brs
Show "Account" option on menu and also do not show package screen after login if already subscribed
=> Fixed APPS-871 and APPS-872

source/services/akamai/roku_malibrary.brs
=> Removed depricated functions

components/screens/GridScreen/GridScreen.brs
Fixed APPS-1069 - "Next Hero Slider" Display Bug
=> Fixed APPS-1069 - "Next Hero Slider" Display Bug

source/helpers.brs
Added support of sorting by Priority into HeroCarousels
=> Added support of sorting by Priority into HeroCarousels

source/services/ZypeServices/MarketplaceConnectService.brs, source/zype_api.brs
=> Implemented Plan Pagination

components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml, source/main.brs
Fixed Issue of naviagtion block for sign in/out.
=> Fixed Issue of naviagtion block for sign in/out.

components/ContentNodes/VideoNode/videonode.xml, components/tasks/MMTask.xml, source/config.tmpl.json, source/main.brs, source/services/MediaMelon/MMSmartStreamEngine.brs, source/services/MediaMelon/MMSmartStreamRokuPlugin.brs, source/services/MediaMelon/MMSmartStreamWrapper.brs, source/services/MediaMelon/Utilities.brs, source/services/ZypeServices/MediaMelonService.brs, source/video-model.brs
Implemented Support for Advanced Analytics.
TODO : Need to verify with subscriptionId.
=> Implemented Support for Advanced Analytics

components/screens/AccountScreen/AccountScreen.brs, components/screens/AuthSelection/AuthSelection.brs, components/screens/CredentialsInput/CredentialsInput.brs, components/screens/DetailsScreen/DetailsScreen.brs, components/screens/GridScreen/GridScreen.brs, components/screens/GridScreen/GridScreen.xml, components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml, components/screens/LoadingScreen/LoadingScreen.brs, components/screens/UniversalAuthSelection/UniversalAuthSelection.brs
- Back handling added for live poster.
- Restricted to press back when preloader is visible on screen.
- Fix issue for clicking on up and show live poster.
- Handling added to click ok on dialog when there is error from video and not able to play.
=> Initial Back Handling issue fixed.

source/main.brs
- Adjust home screen loading indicator.
- Change function name StartLoader to StartLoadingScreen and same for EndLoader to EndLoadingScreen.
- Added two new function StartLoading and EndLoading. Set functions instead of  individual line use to control loader.
=> Adjust home screen loading indicator.

components/tasks/GATrackEventTask.brs, components/tasks/GATrackEventTask.xml, source/config.tmpl.json, source/main.brs, source/services/ZypeServices/GoogleAnalyticsService.brs
Implemented base for Google Analytics.
=> Implemented Google Analytics.

components/screens/GridScreen/GridScreen.brs, components/screens/GridScreen/GridScreen.xml, components/screens/HomeScene/HomeScene.brs, source/helpers.brs, source/main.brs
Fixed crashed for zojbect top-playlist data not found for carousel.
- It will not display carousel if image not found in api response.
=> Fixed crashed for zojbect top-playlist data not found for carousel.

components/screens/HomeScene/HomeScene.brs, components/screens/HomeScene/HomeScene.xml
AppDialogInitiate and AppDialogComplete beacon event added.
=> AppDialogInitiate and AppDialogComplete beacon event added.

source/main.brs
By pass advertisement in deeplinking.
=> By pass advertisement in deeplinking.

source/main.brs
Fixed issue of invalid data of videoobject which blocks to play video.
=> Fixed issue of invalid data of videoobject which blocks to play video.

components/screens/AccountScreen/AccountScreen.brs, components/screens/AccountScreen/AccountScreen.xml, components/screens/AuthSelection/AuthSelection.xml, source/main.brs, source/services/Roku/RokuStoreService/RokuStoreService.brs, source/services/Roku/RokuStoreService/RokuStoreServiceHelpers.brs, source/services/ZypeServices/MarketplaceConnectService.brs
APPS-1486
The goal of this PR was to develop logic within the Roku master template to determine when to show users the ability to subscribe to a free trial within the Account page.
=> Support for Free Trial Handling

source/main.brs, source/services/Roku/RokuStoreService/RokuStoreService.brs, source/services/Roku/RokuStoreService/RokuStoreServiceHelpers.brs, source/services/ZypeServices/MarketplaceConnectService.brs
Updated logic to show plan when has_trialed flag = false.
=> Updated logic to show plan when has_trialed flag = false.

source/playlist-model.brs, source/video-model.brs
=> Fixed thumbnails loading

source/helpers.brs, source/services/MediaMelon/Utilities.brs, source/services/akamai/roku_malibrary.brs
Fixed warning and error for deprecated api.
=> Fixed warning and error for deprecated api.

components/screens/GridScreen/GridScreen.brs, components/screens/HomeScene/HomeScene.brs, source/main.brs, source/utils.brs
Fixed "Home" click issue when user is on 2nd-level playlist.
=> Fixed "Home" click issue when user is on 2nd-level playlist

source/services/akamai/roku_malibrary.brs
Fixed video player crash issue.
=> Fixed Function for Video Player Crashing

source/text_labels_config.json
Extra space removed on exit dialog.
=> Extra space removed on Exit Dialog

components/screens/HomeScene/HomeScene.brs, source/helpers.brs
Extra check added and autoplayhero and limive livestream sorted by priority.
=> Hero Sliders following Zobject Priority Fix

components/ContentNodes/VideoNode/videonode.xml, components/screens/GridScreen/GridScreen.brs, components/screens/GridScreen/GridScreen.xml, source/main.brs, source/resumevideo_functions.brs, source/video-model.brs, source/zype_api.brs
- Added fixed for showing focus on item.
- Fixed deeplink for series and season.
- Stored videoId for playlistId for smartbook mark.
=> Deep Linking fix

components/screens/HomeScene/HomeScene.brs
=> Watch trailer issue fixed
